### ISSUE TITLE
Update to RC2?

### ISSUE THREAD

**Issue by Tazer** [SteelToeOSS/Discovery#1]
Will there be an update to RC2 ? :) Cause I havn't seen any working service discovery for asp.net core RC2 yet.

**Comment by dtillman** [comment]
@Tazer There are RC2 bits on the dev branch... I'll be merging those bits into master in the near future....

You can look at the Fortune Teller sample in the dev branch to see how to use it standalone ... i.e. on your desktop .... or as an app pushed to CloudFoundry.

https://github.com/SteelToeOSS/Samples/tree/dev/Discovery

Dave

**Comment by Tazer** [comment]
Noticed it :) that's way I closed the item.

Thanks for an reply anyway

**Comment by mavenraven** [comment]
Hey @Tazer! I love that you're interested in our project. I was curious how you found out about it, and what's the driving factor in your interest. Thanks for any info!
