### ISSUE TITLE
Getting this error Peer certificate cannot be authenticated with given CA certificate

### ISSUE THREAD

**Issue by gsainagendraprasad** [SteeltoeOSS/Discovery#10]
Hi , I am trying to see how Service Discovery works in PCF Dev. I logged in to pcf dev using cf login -a https://api.local.pcfdev.io --skip-ssl-validation and published both my client and service applications. when i call the client url , i am getting HTTP 500 error, when i saw the logs it says -

2017-04-28T17:26:01.50-0500 [APP/PROC/WEB/0] OUT fail: Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient[0]
2017-04-28T17:26:01.50-0500 [APP/PROC/WEB/0] OUT DoGetApplicationsAsync Exception: System.Net.Http.HttpRequestExce
ption: An error occurred while sending the request. ---> System.Net.Http.CurlException: Peer certificate cannot be authe
nticated with given CA certificates

please help me on this error:

As I was reading through : http://steeltoe.io/docs/steeltoe-discovery/#1-2-2-1-settings-to-discover
this they are saying i may run into ssl certificate issues, is this error related with this ??

**Comment by dtillman** [comment]
Yes, you  will need to disable certificate validation when running on PCF Dev.

**Comment by gsainagendraprasad** [comment]
I did it using this  --skip-ssl-validation while logging in to pcf dev. Still my client is unable to discover the registered service. 

Here is my class :+1: 

   public class ServiceDiscoveryService : IServiceDiscoveryService
    {
        DiscoveryHttpClientHandler _handler;
        private ILogger<ServiceDiscoveryService> _logger;

        private const string RANDOM_FORTUNE_URL = "http://ServiceDiscoveryService/api/values";

        public ServiceDiscoveryService(IDiscoveryClient client, ILogger<ServiceDiscoveryService> logger)
        {
            _handler = new DiscoveryHttpClientHandler(client);

            _logger = logger;
        }

        public  string RandomFortuneAsync()
        {
            _logger?.LogInformation("Before Calling GetClient");
            var client = GetClient();
            _logger?.LogInformation("After Calling GetClient");
            return  (client.GetAsync(RANDOM_FORTUNE_URL).Result).Content.ReadAsStringAsync().Result;
        }

        private HttpClient GetClient()
        {
            var client = new HttpClient(_handler, false);
            return client;
        }
    }

**Comment by dtillman** [comment]
In your appsettings.json files(s), add eureka:client:validate_certificates => false,   the default is true if not specified.

**Comment by gsainagendraprasad** [comment]
@dtillman , I will try this settings and will let you know either way.Thank you.

**Comment by gsainagendraprasad** [comment]
@dtillman, It Worked, my client application is able to call service and fetch data. Thank you.

**Comment by gsainagendraprasad** [comment]
@dtillman , Quick question, What about if a service has multiple versions , how should they get registered in to eureka ?? If spring-application-name is same for all versions then how do we make sure client application is consuming the appropriate version of service ??
