### ISSUE TITLE
Does eureka:client:serviceUrl support HA enabled eureka cluster config?

### ISSUE THREAD

**Issue by yourchanges** [SteeltoeOSS/Discovery#15]
Currently, I use config:
```
"eureka": {
    "client": {
      "serviceUrl": "http://server1:8761/eureka/",
      "shouldFetchRegistry": false,
      "validate_certificates": false
    },
```

it works. but I have two HA enabled eureka servers : server1, server2,  but following config **NOT work**:

```
"eureka": {
    "client": {
      "serviceUrl": "http://server1:8761/eureka/,http://server2:8761/eureka/",
      "shouldFetchRegistry": false,
      "validate_certificates": false
    },
```

any ideas?

**Comment by dtillman** [comment]
It does not support that currently .. I'll have a look at that for a future update

**Comment by yourchanges** [comment]
Thank you!!!

And by the way, another question: Does it support set eureka health check? how to enable it in configure file
