### ISSUE TITLE
Why my service registed host is localhost.localdomain?

### ISSUE THREAD

**Issue by lc273734858** [SteeltoeOSS/Discovery#17]
my appsetting.json 
{
  "spring": {
    "application": {
      "name": "ServiceNetCore"
    }
  },
  "eureka": {
    "client": {
      "serviceUrl": "http://192.168.134.192:8761/eureka/",
      "shouldFetchRegistry": false
      ,"shouldRegisterWithEureka":true
 //"validate_certificates": false
    },
    "instance": {
"hostName":"192.168.1.125",
"port": 5001,
"preferIpAddress":true
    }
  },
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Information",
      "Pivotal": "Debug",
      "Steeltoe": "Debug"
    }
  }
}

but the registed adress is localhost.localdomain

**Comment by lc273734858** [comment]
I used netcore2.0 and publish my application to CentOS7.0

**Comment by dtillman** [comment]
What version of Steeltoe are you using?  (1.0.0 or 1.1.0)?
Dave

**Comment by dtillman** [comment]
Feel free to reopen a new issue you still need help!
