### ISSUE TITLE
Registration error

### ISSUE THREAD

**Issue by GSTQ** [SteeltoeOSS/Discovery#18]
I get the following error when I register a new app in Eureka:
"{
'timestamp':1508239392780,
'status':500,
'error':'Internal Server Error',
'exception':'com.thoughtworks.xstream.converters.ConversionException',
'message':'java.lang.Boolean cannot be cast to java.lang.String : java.lang.Boolean cannot be cast to java.lang.String
---- Debugging information ----
nmessage             : java.lang.Boolean cannot be cast to java.lang.String
ncause-exception     : java.lang.ClassCastException
ncause-message       : java.lang.Boolean cannot be cast to java.lang.String
nclass               : com.netflix.appinfo.InstanceInfo
nrequired-type       : com.netflix.appinfo.InstanceInfo
nconverter-type      : org.springframework.cloud.netflix.eureka.DataCenterAwareMarshallingStrategy$DataCenterAwareConverter
nline number         : -1
nversion             : 1.1.147
-------------------------------',
'path':'/eureka/apps/DOTNET-DEMO-SERVICE'
"

My config is:
"
"spring": {
    "application": {
      "name":  "myDotnetService"
    }
  },
  "eureka": {
    "client": {
      "serviceUrl": "http://my-eureka-instance:8761/eureka/",
      "shouldRegisterWithEureka":true,
      "shouldFetchRegistry": false
    },
    "instance": {
      "app": "myDotnetService",
      "hostName":"my-host",
      "port": "6000"
    }
"

But if i change type of property "Enable" in JsonPortWrapper to String all work as need:
 [JsonProperty("@enabled")]
  public String Enabled { get; private set; }

**Comment by GSTQ** [comment]
I have this local fix, may i do pull requst?

**Comment by dtillman** [comment]
@GSTQ ,
1. What version of Steeltoe are you using? 1.0.0 or 1.1.0?
2. What version of Netflix Eureka are you using or what are you using to startup the Eureka server?
Dave

**Comment by GSTQ** [comment]
1. I'm using Steeltoe  v 1.1.0 from nuget
2. I'm using docker image springcloud/eureka from docker hub. 
At manifest.mf from JAR file i found this: 
![photo_2017-10-30_23-01-40](https://user-images.githubusercontent.com/5313099/32187425-dd061a3a-bdc6-11e7-85a8-41672264ae5b.jpg)

**Comment by dtillman** [comment]
That docker image is very old .. and is likely using old neflix code ..

Can you try running the Eureka server as outlined here: https://github.com/SteeltoeOSS/Samples/blob/master/Discovery/src/AspDotNetCore/Fortune-Teller-Service/README.md ....

I'm sure that works with 1.1.0 as I just ran it again to verify...

or there is a "less" old docker image that we reference in our Music Store sample app that should work fine with 1.1.0.

https://hub.docker.com/r/steeltoeoss/servers

Dave

**Comment by GSTQ** [comment]
Thank you. I'm close my PR.
