### ISSUE TITLE
Service Registry URL not resolved in PCF Marketplace Service

### ISSUE THREAD

**Issue by SivakumarShan** [SteeltoeOSS/Discovery#27]
Hi I have created some sample Service Registry and Discovery applications. This is working fine in Local machine where I installed Eureka server to Register and Discover the services. When I push the same into PCF and bind Service Registry Market Place services to my applications, it's unable to use the Service Registry. It still uses the serviceUrl as http://localhost:8761/eureka/ and not taking the bounded services from VcapServices and throwing an exception while registering and discovering the services. My sample source code can be found here https://github.com/SivakumarShan/steeltoeservicediscovery
Looking for the help to use PCF Service Registry.

Thanks, 
Siva

**Comment by dtillman** [comment]
If you are still having problems, let us know
