### ISSUE TITLE
Eureka Cluster config is not working in the Steeltoe Discovery

### ISSUE THREAD

**Issue by ManteshJ** [SteeltoeOSS/Discovery#29]
I am using the Steeltoe Discovery ClientCore v2.0.1. Eureka Cluster mode configuration is not working.

Single Instance of the Eureka Server config in the Microservice as follows

```
  "eureka": {
    "client": {
      "serviceUrl": "http://localhost:8761/eureka/"
      },
```
The above configuration works fine for single instance of the Eureka Server.

Multi Instances of the Eureka Servers config in the Micro Service as follows
Microservice configuration (appsettings.json)

```
{
  "Logging": {
    "IncludeScopes": true,
    "LogLevel": {
      "Default": "Information",
      "Pivotal": "Debug",
      "Steeltoe": "Debug"
    }
  },
  "spring": {
    "application": {
      "name": "fortuneService"
    }
  },
  "eureka": {
    "client": {
      "serviceUrl": {
        "defaultZone": "http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/"
      },
      "shouldFetchRegistry": true,
      "ValidateCertificates": false,
      "registryFetchIntervalSeconds": 10
    },
    "instance": {
      "appName": "FortuneService",
      "hostName": "localhost",
      "port": 52701,
      "instanceId": "FortuneService2",
      "leaseRenewalIntervalInSeconds": 10,
      "leaseExpirationDurationInSeconds": 5,

      "metadataMap": {
        "zone": "Zone1"
      }
    }
  }
}
```
The above configuration is not working for Eureka Cluster mode. When I used the above configuration, `EurekaClientConfig `always set from the `Default_ServerServiceUrl`
` public const string Default_ServerServiceUrl = "http://localhost:8761/eureka/";`

Why `EurekaClientConfig `set the `Default_ServerServiceUrl  `to the `EurekaServerServiceUrls`? Why it is not taking from configuration(appsettings.json) file?

**Comment by TimHess** [comment]
The history on this issue looks a little confusing, just to bring it all together, @dtillman replied to the issue that was created in Tracker with 

> We currently don't support a list of Eureka server URLs ...
> I've added a story to our backlog to add support for this in the future.
> Dave

The story mentioned above is this one: https://www.pivotaltracker.com/n/projects/1483238/stories/157127296
