### ISSUE TITLE
Why ip address and hostname settings are not considered

### ISSUE THREAD

**Issue by vjmuvva** [SteeltoeOSS/Discovery#3]
I am trying to change the hostname and the ip adress that discovery client uses to register by setting it in the config json - 
"eureka": {
    "client": {
      "serviceUrl": "http://52.77.123.70:8761/eureka/",
      "shouldFetchRegistry": false
    },
    "instance": {
      "hostname": "localhost",
      "ipAddress": "127.0.0.1"
          "preferIpAddress"=true,
          "port": 5001
    }
  }

Looks like hostname, ipAddress, preferIpAddress are not being considered. Any plans of adding this?

**Comment by dtillman** [comment]
@vjmuvva 
Hi Vijay, yes we will add support for preferIpAddress and the other relevant settings in the future.
Dave

**Comment by mavenraven** [comment]
@vjmuvva you can track that progress via https://www.pivotaltracker.com/story/show/127261887

**Comment by dtillman** [comment]
More work still to do to match up with Java client

**Comment by dtillman** [comment]
Ok this should be fully implemented
