### ISSUE TITLE
Is it possible to override the steeltoe configuration(without appsetting.json)?

### ISSUE THREAD

**Issue by ManteshJ** [SteeltoeOSS/Discovery#30]
Hi,

I want to use my own configuration code instead of the SteelToe configuration. Is it possible to override the steeltoe configuration without using appsetting.json?

**Comment by dtillman** [comment]
@ManteshJ : 
Yes, you should be able to ... have a look at the AddDiscoveryClient() methods in this code:

https://github.com/SteeltoeOSS/Discovery/blob/dev/src/Steeltoe.Discovery.ClientCore/DiscoveryServiceCollectionExtensions.cs

Dave
