### ISSUE TITLE
Error message in Eureka server dashboard

### ISSUE THREAD

**Issue by qq57941500** [SteeltoeOSS/Discovery#32]
when .net service is registered with Eureka server, there is an error message in red: 
EMERGENCY! EUREKA MAY BE INCORRECTLY CLAIMING INSTANCES ARE UP WHEN THEY'RE NOT. RENEWALS ARE LESSER THAN THRESHOLD AND HENCE THE INSTANCES ARE NOT BEING EXPIRED JUST TO BE SAFE.

maybe the reason is the .net client is not sending heartbeat message to the server.
Is it possible to add the mechanism or remove the error message somehow?

**Comment by TimHess** [comment]
That message should go away shortly after an app comes online (maybe a couple of minutes?). Does it not go away at all? 

If not:
- are you running a Steeltoe sample, or your own application? 
- is it in a local development environment, cloud foundry or somewhere else?

**Comment by TimHess** [comment]
Closing this issue under the assumption there is no longer a problem, please reopen if you still need help
