### ISSUE TITLE
 Does eureka:client:serviceUrl support multiple eureka servers in the config?

### ISSUE THREAD

**Issue by seanshi90** [SteeltoeOSS/Discovery#33]
Currently, I use config:
"eureka": {
   "client": {
     "serviceUrl": "http://server1:1234/eureka/",
     "shouldFetchRegistry": false,
     "validate_certificates": false
   },
it works. but I have two HA enabled eureka servers : server1, server2, but following config NOT work:

"eureka": {
"client": {
     "serviceUrl": "http://server1:1234/eureka/,http://server2:2234/eureka/",
     "shouldFetchRegistry": false,
     "validate_certificates": false
   },

And I see all the issues about this, I confused that have we fix this issue yet?
Do we have a plan?

**Comment by TimHess** [comment]
Steeltoe Service Discovery does not yet have support for multiple Eureka servers. Support will be added in the future, but timing and implementation specifics have not been decided yet. 

For what it's worth, the Steeltoe implementation will probably be close to what Spring Cloud does

https://github.com/SteeltoeOSS/Discovery/issues/29
https://github.com/SteeltoeOSS/Samples/issues/45

**Comment by seanshi90** [comment]
Thank you very much.  Look forward to the feature added.
