### ISSUE TITLE
Proxy settings are unused

### ISSUE THREAD

**Issue by jlorich** [SteeltoeOSS/Discovery#34]
I am trying to send requests both from client and  server through a proxy but the proxy settings to not seem to be respected.  I can't actually find any use of ProxyHost or ProxyPort outside of loading the configuration settings.  They seem ignored after that.  Are they not supported?

**Comment by TimHess** [comment]
Hi @jlorich,

You're correct, the code to use those settings has not been written yet... We can leave this issue open for visibility, but the story we have to complete the feature is here: https://www.pivotaltracker.com/story/show/157126288

**Comment by petriashev** [comment]
Any progress?

**Comment by petriashev** [comment]
I use https://github.com/micro-elements/MicroElements.FluentProxy for interact with eureka.

**Comment by dtillman** [comment]
@petriashev : We added to 2.2 of Steeltoe usage of the proxy settings in configuration.

Dave
