### ISSUE TITLE
Suport simpleinjector IOC

### ISSUE THREAD

**Issue by poweryang1990** [SteeltoeOSS/Discovery#35]
Hello  
   Can you implement simpleinjector IOC  for Discovery, I 've tried it,  but server can not be regist to Eureka Server

 `  

    public static class DiscoveryContainerExtensions
     {
         public const string EUREKA_PREFIX = "eureka";

         public static void RegisterDiscoveryClient(this Container container, DiscoveryOptions 
           discoveryOptions,IDiscoveryLifecycle lifecycle = null)
           {
            if (container == null)
            {
                throw new ArgumentNullException(nameof(container));
            }

            if (discoveryOptions == null)
            {
                throw new ArgumentNullException(nameof(discoveryOptions));
            }

            if (discoveryOptions.ClientType == DiscoveryClientType.EUREKA)
            {
                EurekaClientOptions clientOptions = discoveryOptions.ClientOptions as EurekaClientOptions;
                if (clientOptions == null)
                {
                    throw new ArgumentException("Missing Client Options");
                }

                container.Register(typeof(IOptionsMonitor<EurekaClientOptions>),()=>new 
            OptionsMonitorWrapper<EurekaClientOptions>(clientOptions),Lifestyle.Singleton);

                var regOptions = discoveryOptions.RegistrationOptions as EurekaInstanceOptions;
                if (regOptions == null)
                {
                    clientOptions.ShouldRegisterWithEureka = false;
                    regOptions = new EurekaInstanceOptions();
                }

                container.Register(typeof(IOptionsMonitor<EurekaInstanceOptions>),()=>new OptionsMonitorWrapper<EurekaInstanceOptions>(regOptions), Lifestyle.Singleton);

                AddEurekaServices(container, lifecycle);
            }
            else
            {
                throw new ArgumentException("Client type UNKNOWN");
            }
        }

        public static void RegisterDiscoveryClient(this Container container, Action<DiscoveryOptions> setupOptions, IDiscoveryLifecycle lifecycle = null)
        {
            if (container == null)
            {
                throw new ArgumentNullException(nameof(container));
            }

            if (setupOptions == null)
            {
                throw new ArgumentNullException(nameof(setupOptions));
            }

            var options = new DiscoveryOptions();
            setupOptions(options);

            container.RegisterDiscoveryClient(options, lifecycle);
        }

        public static void RegisterDiscoveryClient(this Container container, IConfiguration config, IDiscoveryLifecycle lifecycle = null)
        {
            if (container == null)
            {
                throw new ArgumentNullException(nameof(container));
            }

            if (config == null)
            {
                throw new ArgumentNullException(nameof(config));
            }

            AddDiscoveryServices(container, config, lifecycle);
        }

        public static void StartDiscoveryClient(this Container container)
        {
            if (container == null)
            {
                throw new ArgumentNullException(nameof(container));
            }

           
            container.GetInstance<IDiscoveryClient>();
        }

        private static void AddDiscoveryServices(Container container, IConfiguration config, IDiscoveryLifecycle lifecycle)
        {
            var clientConfigsection = config.GetSection(EUREKA_PREFIX);
            int childCount = clientConfigsection.GetChildren().Count();
            if (childCount > 0)
            {
                var clientSection = config.GetSection(EurekaClientOptions.EUREKA_CLIENT_CONFIGURATION_PREFIX);
                container.RegisterOption<EurekaClientOptions>(clientSection);

                container.RegisterPostConfigure<EurekaClientOptions>((options) =>
                {
                   
                });
                var instSection = config.GetSection(EurekaInstanceOptions.EUREKA_INSTANCE_CONFIGURATION_PREFIX);
                container.RegisterOption<EurekaInstanceOptions>(instSection);

                container.RegisterPostConfigure<EurekaInstanceOptions>((options) =>
                {
                    EurekaPostConfigurer.UpdateConfiguration(config, options);
                });
                AddEurekaServices(container, lifecycle);
            }
            else
            {
                throw new ArgumentException("Discovery client type UNKNOWN, check configuration");
            }
        }

        private static void AddEurekaServices(Container container, IDiscoveryLifecycle lifecycle)
        {
            container.Register<EurekaApplicationInfoManager>(Lifestyle.Singleton);
            container.Register<EurekaDiscoveryManager>(Lifestyle.Singleton);
            //container.Register<IDiscoveryClient>(() =>

            //    {
            //        return new EurekaDiscoveryClient(container.GetInstance<IOptionsMonitor<EurekaClientOptions>>(),
            //            container.GetInstance<IOptionsMonitor<EurekaInstanceOptions>>(),
            //            container.GetInstance<EurekaApplicationInfoManager>());
            //    } 

            //,Lifestyle.Singleton);
            container.Register<EurekaDiscoveryClient>(Lifestyle.Singleton);
            container.Register<IEurekaHttpClient>(() =>
            {
                return new EurekaHttpClientInternal(container.GetInstance<IOptionsMonitor<EurekaClientOptions>>(),
                    container.GetInstance<ILoggerFactory>());
            }, Lifestyle.Singleton);
            if (lifecycle == null)
            {
                container.Register<IDiscoveryLifecycle, ApplicationLifecycle>(Lifestyle.Singleton);
            }
            else
            {

                container.Register<IDiscoveryLifecycle>(()=>lifecycle,Lifestyle.Singleton);
            }
            container.Register<IDiscoveryClient>(()=>container.GetInstance<EurekaDiscoveryClient>(),Lifestyle.Singleton);
        }

        public class EurekaHttpClientInternal : EurekaHttpClient
        {
            private IOptionsMonitor<EurekaClientOptions> _configOptions;

            protected override IEurekaClientConfig Config
            {
                get
                {
                    return _configOptions.CurrentValue;
                }
            }

            public EurekaHttpClientInternal(IOptionsMonitor<EurekaClientOptions> config, ILoggerFactory logFactory = null)
            {
                _config = null;
                _configOptions = config ?? throw new ArgumentNullException(nameof(config));
                Initialize(new Dictionary<string, string>(), logFactory);
            }
        }
        public class ApplicationLifecycle : IDiscoveryLifecycle
        {
            private CancellationTokenSource source = new CancellationTokenSource();

            public ApplicationLifecycle()
            {
            }

            public void Shutdown()
            {
                source.Cancel();
            }

            public CancellationToken ApplicationStopping
            {
                get
                {
                    return source.Token;
                }
            }
        }

        public class OptionsMonitorWrapper<T> : IOptionsMonitor<T>
        {
            private T _option;

            public OptionsMonitorWrapper(T option)
            {
                _option = option;
            }

            public T CurrentValue => _option;

            public T Get(string name)
            {
                return _option;
            }

            public IDisposable OnChange(Action<T, string> listener)
            {
                return null;
            }
        }
    }
`

`   

       public static class OptionsContainerExtensions
      {
         public static void RegisterOptions(this Container container)
        {
            if (container == null)
            {
                throw new ArgumentNullException(nameof(container));
            }

            container.Register(typeof(IOptions<>),typeof(OptionsManager<>),Lifestyle.Singleton);
            container.Register(typeof(IOptionsMonitor<>), typeof(OptionsMonitor<>), Lifestyle.Singleton);
            container.Register(typeof(IOptionsMonitorCache<>), typeof(OptionsCache<>), 
      Lifestyle.Singleton);
            container.Register(typeof(IOptionsSnapshot<>), typeof(OptionsManager<>), Lifestyle.Singleton);
            container.Register(typeof(IOptionsFactory<>), typeof(OptionsFactory<>), Lifestyle.Singleton);
        }

        public static void RegisterOption<TOption>(this Container container, IConfiguration config) where TOption : class
        {
            container.RegisterOption<TOption>(Options.DefaultName, config);
        }

        public static void RegisterOption<TOption>(this Container container, string name, IConfiguration config)where TOption : class
        {
            if (container == null)
            {
                throw new ArgumentNullException(nameof(container));
            }

            if (config == null)
            {
                throw new ArgumentNullException(nameof(config));
            }

            container.Register<IOptionsChangeTokenSource<TOption>>(()=>new ConfigurationChangeTokenSource<TOption>(name, config), Lifestyle.Singleton);
            //container.Register<IConfigureOptions<TOption>>(()=>new NamedConfigureFromConfigurationOptions<TOption>(name, config), Lifestyle.Singleton);

            container.Register< IEnumerable<IOptionsChangeTokenSource<TOption>>>(() =>new List<IOptionsChangeTokenSource<TOption>>(){ new ConfigurationChangeTokenSource<TOption>(name, config)}, Lifestyle.Singleton);
            //container.Register<IEnumerable<IConfigureOptions<TOption>>>(() =>new List<IConfigureOptions<TOption>>(){ new NamedConfigureFromConfigurationOptions<TOption>(name, config)}, Lifestyle.Singleton);
        }

        public static void RegisterPostConfigure<TOptions>(this Container container, Action<TOptions> configureOptions)where TOptions : class
        {
            container.RegisterPostConfigure(Options.DefaultName, configureOptions);
        }

        public static void RegisterPostConfigure<TOptions>(this Container container, string name, Action<TOptions> configureOptions)
            where TOptions : class
        {
            if (container == null)
            {
                throw new ArgumentNullException(nameof(container));
            }

            if (configureOptions == null)
            {
                throw new ArgumentNullException(nameof(configureOptions));
            }

            container.Register(typeof(IPostConfigureOptions<TOptions>),()=>new PostConfigureOptions<TOptions>(name, configureOptions),Lifestyle.Singleton);
            //container.Register<IEnumerable<IPostConfigureOptions<TOptions>>>(() => new List<IPostConfigureOptions<TOptions>>() { new PostConfigureOptions<TOptions>(name, configureOptions) }, Lifestyle.Singleton);
        }
    }
`

**Comment by poweryang1990** [comment]
@cf-gitbot  Thanks

**Comment by TimHess** [comment]
Hi @poweryang1990,

Do you have a sample application to go with those classes? We're trying to wrap up some development to get our next release out right now so having an app to work with would greatly speed things up.

**Comment by poweryang1990** [comment]
@TimHess  Sorry, That is My code snippet,It's not running correctly, 
I have pushed to github  . https://github.com/poweryang1990/SpringCloudDemo

**Comment by TimHess** [comment]
@poweryang1990 If I un-comment the IEnumerable registrations you already have in there, this code works for me

**Comment by TimHess** [comment]
@poweryang1990 

1. Were you able to get your code to work?
1. Are you interested in submitting a pull request to add your work?

**Comment by jkonicki** [comment]
Closing.  Reopen in new `steeltoe` repository if this is still an issue.
