### ISSUE TITLE
how to register to multiple eureka server

### ISSUE THREAD

**Issue by akaxb** [SteeltoeOSS/Discovery#36]
we have three eureka server like this :
![image](https://user-images.githubusercontent.com/6300834/41884080-55d15a38-7924-11e8-8e47-225b4aa6d435.png)
so , in my appsettings ,how to set my serviceUrl ，I tried separating them with commas, but it didn't work。
thank you

**Comment by TimHess** [comment]
Sorry, this feature is not supported yet - you are not alone though, and we hear you!

https://github.com/SteeltoeOSS/Samples/issues/45
https://github.com/SteeltoeOSS/Discovery/issues/33

**Comment by dtillman** [comment]
@akaxb : We added this to Steeltoe 2.2.  You can provide a comma delimited list of eureka server urls.
Dave
