### ISSUE TITLE
Cannot evict service from eureka.

### ISSUE THREAD

**Issue by Jamayette** [SteeltoeOSS/Discovery#38]
Hello,
  I am using it with a .net framework project and everything including the service discovery, consume and zuul is fine. The problem is when  I stop my service, the published service stays as registered on the eureka like forever. I wait 5 minutes and it still remains. So  I turned off the self preservation of eureka and the service still remains. Unless I restart the eureka server the service stays registered. I don't think there is something wrong with eureka because my java project works fine. Is there anything wrong?
  thanks!

**Comment by TimHess** [comment]
That does sound unusual, have you tried setting your own value for `eureka:instance:leaseExpirationDurationInSeconds`? By default, your app should stay registered for 90 seconds - you could lower that and `eureka:instance:leaseRenewalIntervalInSeconds` to see if anything changes.

**Comment by TimHess** [comment]
#39 should resolve this issue (thanks @kimbell!) -- That pull request was included in the 2.1.0 release of Steeltoe, please try the updated package and see if that resolves the issue for you!
