### ISSUE TITLE
How to bind multiple Eureka addresses 

### ISSUE THREAD

**Issue by bloodjustice** [SteeltoeOSS/Discovery#42]
How to bind multiple Eureka addresses 
like "serviceUrl": "http://eureka1.fat.com/eureka/,http://eureka2.fat.com/eureka/"

**Comment by sunnycloudy** [comment]
I have the same trouble,  i have tried many google, but there is no  solution satisfied  me.  If we don't implement a client-balance,  why we use eureka?

**Comment by TimHess** [comment]
Using multiple Eureka servers is not currently supported directly, our current recommendation is to use a load balancer in front of your Eureka instances.

This feature is not currently scheduled for our next release, so if it is a high priority, we'd welcome a contribution. I would recommend discussion of implementation before starting the work though, just so we have an understanding of how it should work if anybody does want to pick it up!

https://github.com/SteeltoeOSS/Samples/issues/45

@sunnycloudy I could be wrong, but I'm reading your comment as though you want client-side load balancing in the service discovery, which is different from supporting multiple Eureka servers - Steeltoe already randomly selects from the services registered in Eureka, which is a basic form of client-side load balancing. We are planning to implement something similar to Ribbon with the next release of Steeltoe, but that work has not started yet.

**Comment by sunnycloudy** [comment]
sorry, my ambiguous words may be disturbing, my "client-balance" here just means  "random bind a eureka when other is done".

**Comment by dtillman** [comment]
@sunnycloudy : We added to 2.2 of Steeltoe, the ability to provide a comma delimited list of eureka server urls and implemented logic like what is done by Java Netflix implementation.
