### ISSUE TITLE
How to generate random instance id?

### ISSUE THREAD

**Issue by idilshod87** [SteeltoeOSS/Discovery#48]
I need set port:0 and instanceId: '${spring.application.name}:${spring.application.instance_id:${random.int}}' like in [this](https://cloud.spring.io/spring-cloud-netflix/multi/multi__service_discovery_eureka_clients.html).
How to do it?
Thanks!

**Comment by jkonicki** [comment]
Hello @idilshod87, Property placeholder support is planned for our 2.2.0 release.  W.r.t. the generation of ints, that will likely need to be a separate ticket.

**Comment by dtillman** [comment]
@idilshod87 : 

We added to 2.2. of Steeltoe, a RandomValueBase package to Configuration, so you can now use it to generate random values, similar to Spring Boot apps.  

Also, we added the PropertyPlaceholder package to Configuration so you can use placeholders in your apps configuration.

Dave
