### ISSUE TITLE
provide Client ID and client secret in steel Toe

### ISSUE THREAD

**Issue by VenkateshSrinivasan** [SteeltoeOSS/Discovery#7]
Hi,

I'm using Eureka in Private PCF. The following is my eureka configuration in appSettings.json.
"eureka": {
    "client": {
      "validate_certificates": false,
      "serviceUrl": "https://eureka-82f81597-d68d-462a-89ce-3d68c58b9f29.xxx.com/eureka",
      "shouldFetchRegistry": false
    },
    "instance": {
      "hostName": "eurekaSP.xxx.com",
      "port": 80
    }
  }
How do I provide the client id and client secret for this eureka service in appSettings.json. This is because I'm using the eureka from PCF market place and that requires a client ID and client secret.

**Comment by dtillman** [comment]
@VenkateshSrinivasan : Those will be picked up automatically if you are binding your eureka service to the app. Make sure you are using this Nuget: https://www.nuget.org/packages/Pivotal.Discovery.Client/1.0.0-rc2
