### ISSUE TITLE
Missing connection pooling

### ISSUE THREAD

**Issue by diablo39** [SteeltoeOSS/Discovery#9]
Every time class EurekaHttpClients connects to Eureka server new HttpClient instance is created. New instances of HttpClient results with too many opened TCP connections. EurekaHttpClient should  reuse instance of HttpClient class, for ex. by storing it's reference in field _client, which is already declared.

**Comment by dtillman** [comment]
Thanks,
Added code to dispose of HttpClient.
Changes will be included in upcoming 1.0.1 release.
Dave

**Comment by diablo39** [comment]
Hi,

I was talking about something different. In file https://github.com/SteeltoeOSS/Discovery/blob/dev/src/Steeltoe.Discovery.Eureka.Client/Transport/EurekaHttpClient.cs#L597
you're creating new instance of HttpClient, but you're not assigning it to _client field. 

It means that you're creating new instance of HttpClient every time you're connecting to Eureka.
Simple assignment 
```
_client = client; 
```
will solve the issue.

Best Regards,
Roman
